-- SQL SCRIPT TO CREATE AND MANAGE STUDENT TABLE
-- CREATE STUDENT TABLE
CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTERGER

);

-- INSERT SAMPLE DATA INTO THE STUDENT TABLE

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'RAM', 'DELHI','********', 18),
('2', 'RAMESH', 'GURGOAN','********', 18),
('3', 'SUJIT', 'NOIDA','********', 20),
('4', 'RAJESH', 'GURGOAN','********', 18),
('5', 'RAKESH', 'DELHI','********', 20),
('6', 'RAJAT', 'NOIDA','********', 19);

-- SELECT ALL RECORDS FROM THE STUDENT TABLE TO VERIFY INSERTION

SELECT * FROM STUDENT;

--QUERY STUDENTS WHO ARE 18 YEARS OLD AND LIVE IN DELHI

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

--QUERY STUDENTS WHO ARE 18 YEARS OLD AND NAMED RAM

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

--QUERY STUDENTS NAMED RAM OR SUJIT

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';

--QUERY STUDENTS WHO ARE 18 YEARS OLD AND NAMED RAM OR RAMESH

SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');